### ISSUE TITLE
[Feature Request] Dynamic Conditional Formatting

### ISSUE THREAD

**Issue by haruki-taka8** [haruki-taka8/SF7N#2]
**Is your feature request related to a problem? Please describe.**
Currently, all the condition formatting rules are hard-coded into the .\SF7N-Resources\SF7N-GUI.xaml
It is ideal for users to be able to customize them.

**Describe the solution you'd like**
A new data storage to be implemented that stores the rules.
SF7N should apply the rules by editing the XAML file on startup.

**Comment by haruki-stevefestl** [comment]
Pre-requisite: #1 Dynamic Columns

**Comment by haruki-taka8** [comment]
Pre-requsite is completed; will look into possible code-behind solutions today.

**Comment by haruki-taka8** [comment]
Work started in Testing-DynamicFormatting

**Comment by haruki-taka8** [comment]
Feature implemented into main. Thread closed.
