### ISSUE TITLE
[Bug] Relaunch Messes Up Modules

### ISSUE THREAD

**Issue by haruki-taka8** [haruki-taka8/SF7N#4]
**Describe the bug**
Upon starting, exiting and restarting SF7N in an ISE environment (e.g. PS ISE or VS Code integrated terminal), the modules no longer function. They simply do nothing.

**To Reproduce**
1. Launch SF7N
2. Exit SF7N
3. Relaunch SF7N
4. Everything that is coded in external files (aka modules) are completely unfunctional. 

**Expected Behavior**
SF7N works just like its first launch.

**Environment:**
 - Windows 10
 - 64-bits
 - VS Code Integrated Terminal

**Comment by haruki-stevefestl** [comment]
Bug probably caused by improper cleanup after session/ reset before next launch.

Possible solution: add `$wpf.$formName.Add_Closing()` action

**Comment by haruki-taka8** [comment]
Fixed in 0f4fc6e. Issue closed.
